In [1]:
#Task 1

In [187]:
import pandas as pd
import numpy as np

In [188]:
data=pd.read_csv("diabetes-data.txt")
data.columns = ['Number of times pregnant','Plasma glucose concentration a 2 hours in an oral glucose tolerance test',
                'Diastolic blood pressure (mm Hg)','Triceps skin fold thickness (mm)'
               ,'2-Hour serum insulin (mu U/ml)'
               ,'Body mass index (weight in kg/(height in m)^2)'
               ,'Diabetes pedigree function','Age','Class variable']
X=data.iloc[ : , data.columns != 'Class'].values
Y=data.iloc[:,8].values
data.describe()
df=data
df
print(X)

[['1' '85' '66' ... '0.351' '31' 0]
 ['8' '183' '64' ... '0.672' '32' 1]
 ['1' '89' '66' ... '0.167' '21' 0]
 ...
 ['5' '121' '72' ... '0.245' '30' 0]
 ['1' '126' '60' ... '0.349' '47' 1]
 ['1' '93' '70' ... '0.315' '23' 0]]


In [189]:
df['Number of times pregnant'] = df['Number of times pregnant'].str.replace('?', '')
df['Age'] = df['Age'].str.replace('?', '')
df['Diabetes pedigree function'] = df['Diabetes pedigree function'].str.replace('?', '')
df['Body mass index (weight in kg/(height in m)^2)'] = df['Body mass index (weight in kg/(height in m)^2)'].str.replace('?', '')
df['2-Hour serum insulin (mu U/ml)'] = df['2-Hour serum insulin (mu U/ml)'].str.replace('?', '')
df['Triceps skin fold thickness (mm)'] = df['Triceps skin fold thickness (mm)'].str.replace('?', '')
df['Diastolic blood pressure (mm Hg)'] = df['Diastolic blood pressure (mm Hg)'].str.replace('?', '')
df['Plasma glucose concentration a 2 hours in an oral glucose tolerance test'] = df['Plasma glucose concentration a 2 hours in an oral glucose tolerance test'].str.replace('?', '')

In [196]:
data.mode(axis = 0) 
df=df.apply(pd.to_numeric)
X=df.iloc[ : , data.columns != 'Class'].values
Y=df.iloc[:,8].values
print(X)

[[1.00e+00 8.50e+01 6.60e+01 ... 3.51e-01 3.10e+01 0.00e+00]
 [8.00e+00 1.83e+02 6.40e+01 ... 6.72e-01 3.20e+01 1.00e+00]
 [1.00e+00 8.90e+01 6.60e+01 ... 1.67e-01 2.10e+01 0.00e+00]
 ...
 [5.00e+00 1.21e+02 7.20e+01 ... 2.45e-01 3.00e+01 0.00e+00]
 [1.00e+00 1.26e+02 6.00e+01 ... 3.49e-01 4.70e+01 1.00e+00]
 [1.00e+00 9.30e+01 7.00e+01 ... 3.15e-01 2.30e+01 0.00e+00]]


In [197]:
import pandas as pd
from sklearn import preprocessing

x = df.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
print(x)
x_scaled = min_max_scaler.fit_transform(x)
d2 = pd.DataFrame(x_scaled)


# define a method to scale data, looping thru the columns, and passing a scaler
def scale_data(data, columns, scaler):
    for col in columns:
        data[col] = scaler.fit_transform(data[col].values.reshape(-1, 1))
    return data


[[1.00e+00 8.50e+01 6.60e+01 ... 3.51e-01 3.10e+01 0.00e+00]
 [8.00e+00 1.83e+02 6.40e+01 ... 6.72e-01 3.20e+01 1.00e+00]
 [1.00e+00 8.90e+01 6.60e+01 ... 1.67e-01 2.10e+01 0.00e+00]
 ...
 [5.00e+00 1.21e+02 7.20e+01 ... 2.45e-01 3.00e+01 0.00e+00]
 [1.00e+00 1.26e+02 6.00e+01 ... 3.49e-01 4.70e+01 1.00e+00]
 [1.00e+00 9.30e+01 7.00e+01 ... 3.15e-01 2.30e+01 0.00e+00]]


In [129]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [149]:
array = df.values
X = array[:,0:8]
Y = array[:,8]
print(X)

[[1.00e+00 8.50e+01 6.60e+01 ... 2.66e+01 3.51e-01 3.10e+01]
 [8.00e+00 1.83e+02 6.40e+01 ... 2.33e+01 6.72e-01 3.20e+01]
 [1.00e+00 8.90e+01 6.60e+01 ... 2.81e+01 1.67e-01 2.10e+01]
 ...
 [5.00e+00 1.21e+02 7.20e+01 ... 2.62e+01 2.45e-01 3.00e+01]
 [1.00e+00 1.26e+02 6.00e+01 ... 3.01e+01 3.49e-01 4.70e+01]
 [1.00e+00 9.30e+01 7.00e+01 ... 3.04e+01 3.15e-01 2.30e+01]]


In [150]:

df['Number of times pregnant'] = df['Number of times pregnant'].fillna(df['Number of times pregnant'].median())
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Diabetes pedigree function'] = df['Diabetes pedigree function'].fillna(df['Diabetes pedigree function'].median())
df['Body mass index (weight in kg/(height in m)^2)'] = df['Body mass index (weight in kg/(height in m)^2)'].fillna(df['Body mass index (weight in kg/(height in m)^2)'].median())
df['2-Hour serum insulin (mu U/ml)'] = df['2-Hour serum insulin (mu U/ml)'].fillna(df['2-Hour serum insulin (mu U/ml)'].median())
df['Triceps skin fold thickness (mm)'] = df['Triceps skin fold thickness (mm)'].fillna(df['Triceps skin fold thickness (mm)'].median())
df['Diastolic blood pressure (mm Hg)'] = df['Diastolic blood pressure (mm Hg)'].fillna(df['Diastolic blood pressure (mm Hg)'].median())
df['Plasma glucose concentration a 2 hours in an oral glucose tolerance test'] = df['Plasma glucose concentration a 2 hours in an oral glucose tolerance test'].fillna(df['Plasma glucose concentration a 2 hours in an oral glucose tolerance test'].median())

In [151]:

df['Number of times pregnant'] = df['Number of times pregnant'].fillna(df['Number of times pregnant'].mean())
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Diabetes pedigree function'] = df['Diabetes pedigree function'].fillna(df['Diabetes pedigree function'].mean())
df['Body mass index (weight in kg/(height in m)^2)'] = df['Body mass index (weight in kg/(height in m)^2)'].fillna(df['Body mass index (weight in kg/(height in m)^2)'].mean())
df['2-Hour serum insulin (mu U/ml)'] = df['2-Hour serum insulin (mu U/ml)'].fillna(df['2-Hour serum insulin (mu U/ml)'].mean())
df['Triceps skin fold thickness (mm)'] = df['Triceps skin fold thickness (mm)'].fillna(df['Triceps skin fold thickness (mm)'].mean())
df['Diastolic blood pressure (mm Hg)'] = df['Diastolic blood pressure (mm Hg)'].fillna(df['Diastolic blood pressure (mm Hg)'].mean())
df['Plasma glucose concentration a 2 hours in an oral glucose tolerance test'] = df['Plasma glucose concentration a 2 hours in an oral glucose tolerance test'].fillna(df['Plasma glucose concentration a 2 hours in an oral glucose tolerance test'].mean())

In [152]:
import pandas as pd
import numpy as np
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pd.read_csv(url, names=names)

print(X)
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y)

# Summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)

features = fit.transform(X)
# Summarize selected features
print(features[0:5,:])
model = LogisticRegression()
rfe = RFE(model, 4)
fit = rfe.fit(X, Y)
X = fit.transform(X)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))
print(X)

[[1.00e+00 8.50e+01 6.60e+01 ... 2.66e+01 3.51e-01 3.10e+01]
 [8.00e+00 1.83e+02 6.40e+01 ... 2.33e+01 6.72e-01 3.20e+01]
 [1.00e+00 8.90e+01 6.60e+01 ... 2.81e+01 1.67e-01 2.10e+01]
 ...
 [5.00e+00 1.21e+02 7.20e+01 ... 2.62e+01 2.45e-01 3.00e+01]
 [1.00e+00 1.26e+02 6.00e+01 ... 3.01e+01 3.49e-01 4.70e+01]
 [1.00e+00 9.30e+01 7.00e+01 ... 3.04e+01 3.15e-01 2.30e+01]]
[ 109.767 1405.42    15.365   50.663 1883.23   127.472    5.428  181.909]
[[ 85.    0.   26.6  31. ]
 [183.    0.   23.3  32. ]
 [ 89.   94.   28.1  21. ]
 [137.  168.   43.1  33. ]
 [116.    0.   25.6  30. ]]


C:\Users\haziq\anaconda3\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass n_features_to_select=4 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "
C:\Users\haziq\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\haziq\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of i

Num Features: 4
Selected Features: [ True  True False False False  True  True False]
Feature Ranking: [1 1 3 5 4 1 1 2]
[[1.00e+00 8.50e+01 2.66e+01 3.51e-01]
 [8.00e+00 1.83e+02 2.33e+01 6.72e-01]
 [1.00e+00 8.90e+01 2.81e+01 1.67e-01]
 ...
 [5.00e+00 1.21e+02 2.62e+01 2.45e-01]
 [1.00e+00 1.26e+02 3.01e+01 3.49e-01]
 [1.00e+00 9.30e+01 3.04e+01 3.15e-01]]


In [ ]:
df.describe()
df.isna()
missing = data.isna()
print(missing.sum())
df.loc[[109]]
X=df.iloc[:,:-1].values
Y=df.iloc[:,8].values
df

In [153]:
from collections import Counter
def euclidian_distance(a,b):
    half=np.sum(a-b)**2
    return (np.sqrt(half))

class KNN():

    X_train=0
    Y_train=0
    test_size=45
    k=0
    def __init__(self, k, scalefeatures=False):        
        self.k=k
    def fit(self,x,y):
        self.X_train=x
        self.Y_train=y
        
    
    def Compute_distances(self,X):
        dists=[euclidian_distance(X,x1) for x1 in self.X_train]
        dists2= np.argsort(dists)[:self.k]
        dist3=[self.Y_train[i] for i in dists2]
        dist4= Counter(dist3).most_common(1)
        return dist4[0][0]
    
    def predict(self,X):
        pclass = [self.Compute_distances(x) for x in X ]
        return np.array(pclass)


In [154]:
# Spllit Data into train and test
import Split as t 
Xtrain,Ytrain,Xtest,Ytest=t.split_data(X,Y)
print (" Training Data Set Dimensions=", Xtrain.shape, "Training True Class labels dimensions", Ytrain.shape)   
print (" Test Data Set Dimensions=", Xtest.shape, "Test True Class labels dimensions", Ytrain.shape)  

 Training Data Set Dimensions= (537, 4) Training True Class labels dimensions (537,)
 Test Data Set Dimensions= (230, 4) Test True Class labels dimensions (537,)


In [175]:
# Build a 3-nearest neighbour classifier...
c1=KNN(13)
c1.fit(Xtrain,Ytrain)
predictions = c1.predict(Xtest)
predictions

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1.,
       1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1.,
       1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1.,
       1., 0., 1., 1., 0.

In [176]:
#Check the accuracy on the test set..
accuracy = np.sum(predictions == Ytest)/len(Ytest)
accuracy=accuracy*100
print(accuracy,"%")


79.13043478260869 %


In [185]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 11)
classifier.fit(Xtrain,Ytrain)
y_pred = classifier.predict(Xtest)

In [186]:
accuracy = np.sum(y_pred== Ytest)/len(Ytest)
accuracy=accuracy*100
print(accuracy,"%")


77.39130434782608 %


In [107]:
df2=pd.read_csv("hepatitis-data.txt")

In [108]:
df2

2  30  2.1  1  2.2 2.3 2.4 2.5 1.1 2.6 2.7 2.8 2.9 2.10  1.00   85   18  \
0    2  50    1  1    2   1   2   2   1   2   2   2   2    2  0.90  135   42   
1    2  78    1  2    2   1   2   2   2   2   2   2   2    2  0.70   96   32   
2    2  31    1  ?    1   2   2   2   2   2   2   2   2    2  0.70   46   52   
3    2  34    1  2    2   2   2   2   2   2   2   2   2    2  1.00    ?  200   
4    2  34    1  2    2   2   2   2   2   2   2   2   2    2  0.90   95   28   
..  ..  ..  ... ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ...   ...  ...  ...   
149  1  46    1  2    2   1   1   1   2   2   2   1   1    1  7.60    ?  242   
150  2  44    1  2    2   1   2   2   2   1   2   2   2    2  0.90  126  142   
151  2  61    1  1    2   1   1   2   1   1   2   1   2    2  0.80   75   20   
152  2  53    2  1    2   1   2   2   2   2   1   1   2    1  1.50   81   19   
153  1  43    1  2    2   1   2   2   2   2   1   1   1    2  1.20  100   19   

     4.0   ?  1.2  
0    3.5   ?    1  
1    4.0   ?    1  
2    4.0  80    1  
3    4.0   ?    1  
4    4.0  75    1  
..   ...  ..  ...  
149  3.3  50    2  
150  4.3   ?    2  
151  4.1   ?    2  
152  4.1  48    2  
153  3.1  42    2  

[154 rows x 20 columns]

In [109]:
   df2.columns=['Class'
      ,'AGE'
      ,'SEX'
      ,'STEROID'
      ,'ANTIVIRALS'
      ,'FATIGUE'
      ,'MALAISE'
     , 'ANOREXIA'
     , 'LIVER BIG'
     ,'LIVER FIRM'
     ,'SPLEEN PALPABLE'
     ,'SPIDERS'
     ,'ASCITES'
     ,'VARICES'
     ,'BILIRUBIN'
     ,'ALK PHOSPHATE'
     ,'SGOT'
     ,'ALBUMIN'
     ,'PROTIME'
     ,'HISTOLOGY']


In [110]:
df2

Class  AGE  SEX STEROID  ANTIVIRALS FATIGUE MALAISE ANOREXIA LIVER BIG  \
0        2   50    1       1           2       1       2        2         1   
1        2   78    1       2           2       1       2        2         2   
2        2   31    1       ?           1       2       2        2         2   
3        2   34    1       2           2       2       2        2         2   
4        2   34    1       2           2       2       2        2         2   
..     ...  ...  ...     ...         ...     ...     ...      ...       ...   
149      1   46    1       2           2       1       1        1         2   
150      2   44    1       2           2       1       2        2         2   
151      2   61    1       1           2       1       1        2         1   
152      2   53    2       1           2       1       2        2         2   
153      1   43    1       2           2       1       2        2         2   

    LIVER FIRM SPLEEN PALPABLE SPIDERS ASCITES VARICES BILIRUBIN  \
0            2               2       2       2       2      0.90   
1            2               2       2       2       2      0.70   
2            2               2       2       2       2      0.70   
3            2               2       2       2       2      1.00   
4            2               2       2       2       2      0.90   
..         ...             ...     ...     ...     ...       ...   
149          2               2       1       1       1      7.60   
150          1               2       2       2       2      0.90   
151          1               2       1       2       2      0.80   
152          2               1       1       2       1      1.50   
153          2               1       1       1       2      1.20   

    ALK PHOSPHATE SGOT ALBUMIN PROTIME  HISTOLOGY  
0             135   42     3.5       ?          1  
1              96   32     4.0       ?          1  
2              46   52     4.0      80          1  
3               ?  200     4.0       ?          1  
4              95   28     4.0      75          1  
..            ...  ...     ...     ...        ...  
149             ?  242     3.3      50          2  
150           126  142     4.3       ?          2  
151            75   20     4.1       ?          2  
152            81   19     4.1      48          2  
153           100   19     3.1      42          2  

[154 rows x 20 columns]

In [111]:
df2.describe()


Class         AGE         SEX  ANTIVIRALS   HISTOLOGY
count  154.000000  154.000000  154.000000  154.000000  154.000000
mean     1.792208   41.272727    1.097403    1.844156    1.454545
std      0.407051   12.574106    0.297473    0.363891    0.499554
min      1.000000    7.000000    1.000000    1.000000    1.000000
25%      2.000000   32.000000    1.000000    2.000000    1.000000
50%      2.000000   39.000000    1.000000    2.000000    1.000000
75%      2.000000   50.000000    1.000000    2.000000    2.000000
max      2.000000   78.000000    2.000000    2.000000    2.000000

In [112]:
df2['STEROID'] = df2['STEROID'].str.replace('?', '')
df2['FATIGUE'] = df2['FATIGUE'].str.replace('?', '')
df2['MALAISE'] = df2['MALAISE'].str.replace('?', '')
df2['ANOREXIA'] = df2['ANOREXIA'].str.replace('?', '')
df2['LIVER BIG'] = df2['LIVER BIG'].str.replace('?', '')
df2['LIVER FIRM'] = df2['LIVER FIRM'].str.replace('?', '')
df2['SPLEEN PALPABLE'] = df2['SPLEEN PALPABLE'].str.replace('?', '')
df2['SPIDERS'] = df2['SPIDERS'].str.replace('?', '')
df2['ASCITES'] = df2['ASCITES'].str.replace('?', '')
df2['VARICES'] = df2['VARICES'].str.replace('?', '')
df2['BILIRUBIN'] = df2['BILIRUBIN'].str.replace('?', '')
df2['ALK PHOSPHATE'] = df2['ALK PHOSPHATE'].str.replace('?', '')
df2['SGOT'] = df2['SGOT'].str.replace('?', '')
df2['ALBUMIN'] = df2['ALBUMIN'].str.replace('?', '')
df2['PROTIME'] = df2['PROTIME'].str.replace('?', '')


In [113]:
df2 = df2.apply(pd.to_numeric)

In [114]:
df2['STEROID'] = df2['STEROID'].fillna(df2['STEROID'].median())
df2['FATIGUE'] = df2['FATIGUE'].fillna(df2['FATIGUE'].median())
df2['MALAISE'] = df2['MALAISE'].fillna(df2['MALAISE'].median())
df2['ANOREXIA'] = df2['ANOREXIA'].fillna(df2['ANOREXIA'].median())
df2['LIVER BIG'] = df2['LIVER BIG'].fillna(df2['LIVER BIG'].median())
df2['LIVER FIRM'] = df2['LIVER FIRM'].fillna(df2['LIVER FIRM'].median())
df2['SPLEEN PALPABLE'] = df2['SPLEEN PALPABLE'].fillna(df2['SPLEEN PALPABLE'].median())
df2['SPIDERS'] = df2['SPIDERS'].fillna(df2['SPIDERS'].median())
df2['ASCITES'] = df2['ASCITES'].fillna(df2['ASCITES'].median())
df2['VARICES'] = df2['VARICES'].fillna(df2['VARICES'].median())
df2['BILIRUBIN'] = df2['BILIRUBIN'].fillna(df2['BILIRUBIN'].median())
df2['ALK PHOSPHATE'] = df2['ALK PHOSPHATE'].fillna(df2['ALK PHOSPHATE'].median())
df2['SGOT'] = df2['SGOT'].fillna(df2['SGOT'].median())
df2['ALBUMIN'] = df2['ALBUMIN'].fillna(df2['ALBUMIN'].median())
df2['PROTIME'] = df2['PROTIME'].fillna(df2['PROTIME'].median())

In [115]:
Y=df2.iloc[:, 0].values
X=df2.iloc[ : , df2.columns != 'Class'].values

In [131]:
X

array([[1.00e+00, 8.50e+01, 6.60e+01, ..., 3.51e-01, 3.10e+01, 0.00e+00],
       [8.00e+00, 1.83e+02, 6.40e+01, ..., 6.72e-01, 3.20e+01, 1.00e+00],
       [1.00e+00, 8.90e+01, 6.60e+01, ..., 1.67e-01, 2.10e+01, 0.00e+00],
       ...,
       [5.00e+00, 1.21e+02, 7.20e+01, ..., 2.45e-01, 3.00e+01, 0.00e+00],
       [1.00e+00, 1.26e+02, 6.00e+01, ..., 3.49e-01, 4.70e+01, 1.00e+00],
       [1.00e+00, 9.30e+01, 7.00e+01, ..., 3.15e-01, 2.30e+01, 0.00e+00]])

In [117]:
# Spllit Data into train and test
import Split as t 
Xtrain,Ytrain,Xtest,Ytest=t.split_data(X,Y)
print (" Training Data Set Dimensions=", Xtrain.shape, "Training True Class labels dimensions", Ytrain.shape)   
print (" Test Data Set Dimensions=", Xtest.shape, "Test True Class labels dimensions", Ytrain.shape)  

 Training Data Set Dimensions= (107, 19) Training True Class labels dimensions (107,)
 Test Data Set Dimensions= (47, 19) Test True Class labels dimensions (107,)


In [118]:
# Build a 3-nearest neighbour classifier...
c1=KNN(10)
c1.fit(Xtrain,Ytrain)
predictions = c1.predict(Xtest)
predictions

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2], dtype=int64)

In [119]:
accuracy = np.sum(predictions== Ytest)/len(Ytest)
accuracy=accuracy*100
print(accuracy,"%")


78.72340425531915 %


In [120]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 10)
classifier.fit(Xtrain,Ytrain)
y_pred = classifier.predict(Xtest)

In [121]:
accuracy = np.sum(y_pred== Ytest)/len(Ytest)
accuracy=accuracy*100
print(accuracy,"%")


78.72340425531915 %
